export const color={
    blue: "#3194e2",
    skyBlue: "#93c7f0",
    white: "#ffffff",
    black: "#000000",
    red: "#ff0000",
    grey: "#a6a6a6",
    lightGrey: "#f2f2f2",
    lightPink: "#eec5c2",
    salmon: "#ee7d73",
    lightYellow: "#ede7dc",
    darkPink: "#e48981",
    characterYellow: "#ffe097",
    pink: "#f6c3c1",
    grey: "#eaeaea",
    ppink:"#ffc1c0",
    pale: "#ffd4d4",
};

export const theme = {
    bottomtabtint: "#ee7d73",
    whiteBackground: color.white,
    blackText: color.black,
    pinkTheme: color.lightPink,
    focusedIconLabel : color.salmon,
    diaryBackdround: color.lightYellow,
    darkPinkIcon: color.darkPink,
    toggleTrue: color.salmon,
    toggleFalse: color.grey,
    toggleThumb: color.white,
    characterYellow: color.characterYellow,
    diaryborder : color.pink,
    monthcolor: color.pink,
    modalpink : color.pink,
    greybutton: color.grey,
    pinkbutton: color.ppink,
    diaryadd: color.pale,
};